version: 0.2

phases:
  install:
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
      - curl -fsSL https://raw.githubusercontent.com/thii/aws-codebuild-extras/master/install >> extras.sh
      - . ./extras.sh
  pre_build:
    commands:
      - echo "AWS Login"
      - $(aws ecr get-login --registry-ids $AWS_ACCOUNT_ID --no-include-email --region $AWS_DEFAULT_REGION)
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$CODEBUILD_GIT_BRANCH
      - echo "Tagging Done."
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images....
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$CODEBUILD_GIT_BRANCH
      - echo Writing image definitions file...
      - printf '[{"name":"demo","imageUri":"%s"}]' $REPOSITORY_URI:$CODEBUILD_GIT_BRANCH > imagedefinitions.json
artifacts:
    files: imagedefinitions.json